### ISSUE TITLE
source code issue: processed= spelled wrong, I think. 2 c's on second one. There is no var proccessed that I can see.

### ISSUE THREAD

**Issue by eckgar** [anantdgoel/HackPrincetonF16#10]
var picComment = test[i].querySelector('.uiScaledImageContainer._4-ep');
			if(picComment != null && picComment.src!=undefined) {
				//console.log(picComment);
				httpGet(picComment.src, "image", data);
				processed = false;
			}

			var picPost = test[i].querySelector('._46-h._517g');
			if(!processed && picPost != null && picPost.src!=undefined) {
				//console.log(picPost);
				httpGet(picPost.src, "image", data);
				proccessed = false;

**Comment by jaredpavan** [comment]
Good catch. I created a PR to fix this typo: https://github.com/anantdgoel/HackPrincetonF16/pull/12
