### ISSUE TITLE
Not seeing any badges - possible CORS issue

### ISSUE THREAD

**Issue by dchersey** [anantdgoel/HackPrincetonF16#28]
Hello,

First of all ... friggen' great idea!  I'm looking forward to helping this come alive in any way I can. 
I'm a developer with an non-profit organization that is actively looking for ways to apply technology to the way we live, relate, communicate and operate in the world so we can all thrive together. This fits right in; if we tell when we are reading or spreading disinformation we can choose not to do it and increase the chances of finding truth. 
</soapbox>

Second -- a possibly dumb question but I have installed this in chrome and I do not see any verified/unverified badges in my newsfeed.  Not clear whether I should see one on every post or only those that can be reliably verified or discredited.  I haven't actually tried posting any fake news yet -- do you have an example I could try to see if that is working? 

Thanks for all your work on this!  It's a very powerful idea and I'd like to help in any way I can.

**Comment by dchersey** [comment]
Further investigation ... I see 
```
Fetch API cannot load https://trustfb.herokuapp.com/?content=http:canal311.com/en/sex-education-for-children-norways-tv-6/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://ofpheinlpjdffpdakjegbcphdfeekpnn' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
in the javascript console.  Is this part of the backend? If so, probably what is preventing this from working.

**Comment by lewisje** [comment]
Neither this service, nor the dev service pointed to in the repo, is currently set up; I hope the better backend server they were talking about gets set up soon.

**Comment by dchersey** [comment]
Ok, thanks.  Appreciate all the work everyone is putting into this!

**Comment by lewisje** [comment]
Lately I have been seeing the badges, so it looks like the services have been set up.

**Comment by anantdgoel** [comment]
This was fixed a while ago, so I am gonna go ahead and close this.
Here is a link to the extension that uses an upgraded set of our APIs: https://chrome.google.com/webstore/detail/project-fib/njfkbbdphllgkbdomopoiibhdkkohnbf

**Comment by gvaldez81** [comment]
Question, the source code of final project wont be available to the public? Im guessing not because of your last comment @anantdgoel ...
