### ISSUE TITLE
Perhaps AWS lambda over Heroku?

### ISSUE THREAD

**Issue by brianneisler** [anantdgoel/HackPrincetonF16#3]
Hey all, seems like your hack project blew up today ;) Congrats on all the traction.

Just a suggestion but you may want to look at moving over to something like AWS lambda to scale out your backend a bit more seamlessly. Seems like it might be a pretty good fit given the nature of the backend code is relatively stateless.

**Comment by anantdgoel** [comment]
Yes, this will be happening, we are waiting for an approval from Amazon regarding some AWS credit
