### ISSUE TITLE
Chrome store url is incorrect

### ISSUE THREAD

**Issue by teledyn** [anantdgoel/HackPrincetonF16#30]
https://chrome.google.com/webstore/detail/fib/ofpheinlpjdffpdakjegbcphdfeekpnn leads to a 404

**Comment by J2TEAM** [comment]
I think it was removed from Chrome Store (or hidden by the developers).

![image](https://cloud.githubusercontent.com/assets/5250117/20633394/a45b0262-b378-11e6-9c92-eb26247e349f.png)

**Comment by martinstavrovsky** [comment]
Confirming the link does not work, also searching for any of the keywords inside chrome webstore returns no results.

**Comment by anantdgoel** [comment]
We will be back up soon! Google is just reviewing our new code.

**Comment by anantdgoel** [comment]
It is back up at https://chrome.google.com/webstore/detail/project-fib/njfkbbdphllgkbdomopoiibhdkkohnbf
