### ISSUE TITLE
Docker image does not build and run properly

### ISSUE THREAD

**Issue by bonedaddy** [anantdgoel/HackPrincetonF16#31]
**root@openmediavault:/Data/Docker/HackPrincetonF16/backend# docker run -it --rm -p 5000:5000 hackprincetonf16**
Unable to find image 'hackprincetonf16:latest' locally
Pulling repository docker.io/library/hackprincetonf16
docker: Error: image library/hackprincetonf16:latest not found.
See 'docker run --help'.
root@openmediavault:/Data/Docker/HackPrincetonF16/backend# ^C
**root@openmediavault:/Data/Docker/HackPrincetonF16/backend# docker build -t hackprincetonf16 .**
Sending build context to Docker daemon  34.3 kB
Step 1 : FROM python:3.5.2-alpine
 ---> 7aa75d330a28
Step 2 : MAINTAINER Micheal Waltz <ecliptik@gmail.com>
 ---> Using cache
 ---> 26d679110053
Step 3 : ENV APP_DIR /app
 ---> Using cache
 ---> bb0e28124894
Step 4 : EXPOSE 5000
 ---> Using cache
 ---> 29d548e505ce
Step 5 : WORKDIR ${APP_DIR}
 ---> Using cache
 ---> 90da559c7fe2
Step 6 : RUN mkdir -p ${APP_DIR}
 ---> Using cache
 ---> 1845352ddbc6
Step 7 : COPY requirements.txt ${APP_DIR}/
 ---> Using cache
 ---> b1a94050da2f
Step 8 : RUN apk --no-cache add         --virtual build-dependencies           build-base &&     pip install -U -r requirements.txt &&     apk del build-dependencies
 ---> Using cache
 ---> 392166fdf27c
Step 9 : COPY *.py ${APP_DIR}/
No source files were specified
**root@openmediavault:/Data/Docker/HackPrincetonF16/backend# docker run -it --rm -p 5000:5000 hackprincetonf16**
Unable to find image 'hackprincetonf16:latest' locally
Pulling repository docker.io/library/hackprincetonf16
docker: Error: image library/hackprincetonf16:latest not found.
See 'docker run --help'.

**Comment by santteegt** [comment]
Hello,

Replace the following at the end of the Dockerfile:

```
COPY app/* ${APP_DIR}/
```

**Comment by KirstensGitHub** [comment]
^ I had the same problem and replaced the line above with success. Should this be changed in the repo? (Also, I still have not gotten anything to show up in my fb feed yet; when I view fb docker gives this error in terminal repeatedly: `code 400, message Bad request syntax` )

**Comment by KirstensGitHub** [comment]
or `message Bad request version` or `message Bad request type`

**Comment by anantdgoel** [comment]
You can get the chome extension here instead: https://chrome.google.com/webstore/detail/project-fib/njfkbbdphllgkbdomopoiibhdkkohnbf

The bad requests exist because we flushed all credentials used in this github repo from our servers to make them more secure.

**Comment by KirstensGitHub** [comment]
okay, thanks! I've installed the extension but still not seeing badges..

**Comment by anantdgoel** [comment]
Can you send me a few of the links for which the badges arent being shown? I'll run them manually on our backend to debug this issue

**Comment by anantdgoel** [comment]
@KirstensGitHub Can you check if the extension works for you now? You should see the badges after today's updates!
