### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ceased-ebc** [anantdgoel/HackPrincetonF16#33]
...

**Comment by eckgar** [comment]
in manifest.json change
"matches": ["https://www.facebook.com/*"]
to
`"matches": [ "*://*/*" ],`

**Comment by WilliamJamesDalrympleWest** [comment]
Understood so just change Manifest.json "fb" to "invacio" .

Any specific file(s) that control the location and display style/design of the notification? 

Many thanks.

**Comment by anantdgoel** [comment]
Just changing the URL property will not help you web scrape all sites, you scrape another site. You need to look into div tags and DOMS. Same goes for notification location and design. You need to learn about their DOMs and manipulate it.
