### ISSUE TITLE
Color contrast issues

### ISSUE THREAD

**Issue by pll33** [anantdgoel/HackPrincetonF16#35]
Hey, I recently came across the [Washington Post article](https://www.washingtonpost.com/news/inspired-life/wp/2016/11/18/fake-news-on-facebook-is-a-real-problem-these-college-students-came-up-with-a-fix/) about your project through a [recent story about fake news](http://thephiladelphiacitizen.org/george-ciccariello-maher-white-genocide-tweet/). Congrats on being featured!

Very interesting stuff, but I couldn't help but notice the color contrast on the verification badges ([verified](https://img.washingtonpost.com/news/inspired-life/wp-content/uploads/sites/44/2016/11/Screen-Shot-2016-11-17-at-3-53-39-PM-002.png), [unverified](https://img.washingtonpost.com/news/inspired-life/wp-content/uploads/sites/44/2016/11/Screen-Shot-2016-11-17-at-4-58-10-PM-002.png)) made it hard to see and read. Especially for those with color blindness/deficiency problems, it would be difficult to see the unverified badge ([deuteranope](http://i.imgur.com/arZ3LzF.jpg)).

I fumbled around with color combinations for a few minutes and while not perfect, here's [what I came up with](http://i.imgur.com/jlopAw1.png) ([deuteranope](http://i.imgur.com/ebbGPsJ.jpg)). Feel free to use that or another high-contrast combination (see: [color contrast tool](http://webaim.org/resources/contrastchecker/)).

Though not a huge technical problem, I think it would definitely help with visibility when someone uses the tool in the future.

Thanks for your work and keep it up!

**Comment by anantdgoel** [comment]
Yellow and Green, while having a great contrast, do not fit into the general theme of Facebook's website and would be an eyesore to anyone using this extension. However, I will look into this concept and see how we can improve our color scheme. Thanks!
