### ISSUE TITLE
If you want some help

### ISSUE THREAD

**Issue by jcii** [anantdgoel/HackPrincetonF16#4]
Howdy,

Hey if you want some help, I'm a release engineer/devops'y software engineer in Seattle. If you look at my org here (https://github.com/SavageLearning) you'll see I have a long running open source project for a Seattle non-profit. I'd be happy to help if I can. 

-jimmy

**Comment by anantdgoel** [comment]
Shoot me an email at anantdgoel@gmail.com and we can definitely discuss this. I am sure we could use some help.

**Comment by arshadop44** [comment]
email me at marshad@matchpointsolutions.com. I have an interesting project for you.
