### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by antoniomedrano** [anantdgoel/HackPrincetonF16#7]
Super cool project! Would be nice to have some documentation though. Even just a README.md introducing the plug-in would be nice

**Comment by lanpaje** [comment]
I can probably come up with something like this by tonight.

**Comment by antoniomedrano** [comment]
Might also want to add some contributing guidelines. For example, we use this for our open-source projects:
https://github.com/arogi/internal-demos/blob/master/CONTRIBUTING.md

**Comment by anantdgoel** [comment]
Thanks for the suggestion. Literally using your contribution guide.
